/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client.view;

import javax.swing.JOptionPane;
import client.controller.ClientController;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Pedro Henrique
 */
public class ClientView extends javax.swing.JFrame {

    private ClientController controller;

    /**
     * Creates new form ClientView
     */
    public ClientView() {
        initComponents();
        controller = new ClientController("127.0.0.1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoCadastroCliente = new javax.swing.JButton();
        BotaoCadastroQuarto = new javax.swing.JButton();
        BotaoConsultarQuartosData = new javax.swing.JButton();
        BotaoFazerReserva = new javax.swing.JButton();
        BotaoBuscarReservaCPF = new javax.swing.JButton();
        BotaoCancelarReservaID = new javax.swing.JButton();
        BotaoListarQuartos = new javax.swing.JButton();
        BotaoListarReservas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoCadastroCliente.setText("Cadastrar Cliente");
        botaoCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroClienteActionPerformed(evt);
            }
        });

        BotaoCadastroQuarto.setText("Cadastrar Quarto");
        BotaoCadastroQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroQuartoActionPerformed(evt);
            }
        });

        BotaoConsultarQuartosData.setText("Consultar quartos disponiveis em uma data");
        BotaoConsultarQuartosData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConsultarQuartosDataActionPerformed(evt);
            }
        });

        BotaoFazerReserva.setText("Fazer Reserva");
        BotaoFazerReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFazerReservaActionPerformed(evt);
            }
        });

        BotaoBuscarReservaCPF.setText("Buscar reserva por CPF");
        BotaoBuscarReservaCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscarReservaCPFActionPerformed(evt);
            }
        });

        BotaoCancelarReservaID.setText("Cancelar reserva por ID");
        BotaoCancelarReservaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarReservaIDActionPerformed(evt);
            }
        });

        BotaoListarQuartos.setText("Listar todos os quartos");
        BotaoListarQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoListarQuartosActionPerformed(evt);
            }
        });

        BotaoListarReservas.setText("Listar todas as reservas");
        BotaoListarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoListarReservasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoListarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoListarQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoCancelarReservaID, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoBuscarReservaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BotaoCadastroQuarto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoConsultarQuartosData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoCadastroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoFazerReserva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BotaoBuscarReservaCPF, BotaoCadastroQuarto, BotaoCancelarReservaID, BotaoConsultarQuartosData, BotaoFazerReserva, BotaoListarQuartos, BotaoListarReservas, botaoCadastroCliente});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoCadastroQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoConsultarQuartosData, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoFazerReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoBuscarReservaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoCancelarReservaID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoListarQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoListarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BotaoBuscarReservaCPF, BotaoCadastroQuarto, BotaoCancelarReservaID, BotaoConsultarQuartosData, BotaoFazerReserva, BotaoListarQuartos, BotaoListarReservas, botaoCadastroCliente});

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroClienteActionPerformed
        // TODO add your handling code here:
        String nome = JOptionPane.showInputDialog(this, "Digite o nome do cliente:");
        String cpf = JOptionPane.showInputDialog(this, "Digite o CPF do cliente:");
        try {
            String resultado = controller.getService().cadastrar(nome, cpf);
            JOptionPane.showMessageDialog(this, resultado);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar cliente: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoCadastroClienteActionPerformed

    private void BotaoCadastroQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroQuartoActionPerformed
        // TODO add your handling code here:
        try {
            int numero = Integer.parseInt(JOptionPane.showInputDialog(this, "Número do quarto:"));
            String valorStr = JOptionPane.showInputDialog(this, "Valor da diária:");
            BigDecimal valor = new BigDecimal(valorStr.replace(",", "."));
            int tipo = Integer.parseInt(JOptionPane.showInputDialog(this, "Tipo do quarto (1=Standard, 2=Duplo...):"));
            String resultado = controller.getService().cadastrarQuarto(numero, valor, tipo);
            JOptionPane.showMessageDialog(this, resultado);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar quarto: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotaoCadastroQuartoActionPerformed

    private void BotaoConsultarQuartosDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConsultarQuartosDataActionPerformed
        // TODO add your handling code here:
        try {
            String dataStr = JOptionPane.showInputDialog(this, "Data (dd/MM/yyyy):");
            Date data = new SimpleDateFormat("dd/MM/yyyy").parse(dataStr);
            List<server.model.Quarto> disponiveis = controller.getService().consultarQuartosDisponveis(data);
            StringBuilder sb = new StringBuilder("Quartos disponíveis:\n");
            for (var q : disponiveis) {
                sb.append(q).append("\n");
            }
            JOptionPane.showMessageDialog(this, sb.toString());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao consultar quartos: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotaoConsultarQuartosDataActionPerformed

    private void BotaoFazerReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFazerReservaActionPerformed
        try {
            String cpf = JOptionPane.showInputDialog(this, "CPF do cliente:");
            String entradaStr = JOptionPane.showInputDialog(this, "Data de entrada (dd/MM/yyyy):");
            String saidaStr = JOptionPane.showInputDialog(this, "Data de saída (dd/MM/yyyy):");
            int numero = Integer.parseInt(JOptionPane.showInputDialog(this, "Número do quarto:"));

            Date entrada = new SimpleDateFormat("dd/MM/yyyy").parse(entradaStr);
            Date saida = new SimpleDateFormat("dd/MM/yyyy").parse(saidaStr);

            String resultado = controller.getService().fazerReserva(entrada, saida, cpf, numero);
            JOptionPane.showMessageDialog(this, resultado);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao fazer reserva: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotaoFazerReservaActionPerformed

    private void BotaoBuscarReservaCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscarReservaCPFActionPerformed
        // TODO add your handling code here:
        String cpf = JOptionPane.showInputDialog(this, "Digite o CPF para buscar reserva:");
        try {
            String resultado = controller.getService().buscarReserva(cpf);
            JOptionPane.showMessageDialog(this, "Resultado:\n" + resultado);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar reserva: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotaoBuscarReservaCPFActionPerformed

    private void BotaoCancelarReservaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarReservaIDActionPerformed
        // TODO add your handling code here:
        try {
            Long id = Long.parseLong(JOptionPane.showInputDialog(this, "Digite o ID da reserva:"));
            String resultado = controller.getService().cancelarReserva(id);
            JOptionPane.showMessageDialog(this, resultado);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao cancelar reserva: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotaoCancelarReservaIDActionPerformed

    private void BotaoListarQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoListarQuartosActionPerformed
        // TODO add your handling code here:
        try {
            List<server.model.Quarto> quartos = controller.getService().listarQuartosDisponiveis();
            StringBuilder sb = new StringBuilder("Quartos disponíveis:\n");
            for (var q : quartos) {
                sb.append(q).append("\n");
            }
            JOptionPane.showMessageDialog(this, sb.toString());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao listar quartos: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotaoListarQuartosActionPerformed

    private void BotaoListarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoListarReservasActionPerformed
        // TODO add your handling code here:
        try {
            var reservas = controller.getService().listarReservas();
            StringBuilder sb = new StringBuilder("Reservas:\n");
            for (var r : reservas) {
                sb.append(r).append("\n");
            }
            JOptionPane.showMessageDialog(this, sb.toString());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao listar reservas: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotaoListarReservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoBuscarReservaCPF;
    private javax.swing.JButton BotaoCadastroQuarto;
    private javax.swing.JButton BotaoCancelarReservaID;
    private javax.swing.JButton BotaoConsultarQuartosData;
    private javax.swing.JButton BotaoFazerReserva;
    private javax.swing.JButton BotaoListarQuartos;
    private javax.swing.JButton BotaoListarReservas;
    private javax.swing.JButton botaoCadastroCliente;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
